update tournament set chinese_name = '澳大利亚公开赛' where tournament_id ='1';
update tournament set chinese_name = '洛杉矶' where tournament_id ='2';
update tournament set chinese_name = '辛辛那提大师赛' where tournament_id ='3';
update tournament set chinese_name = '巴塞罗那' where tournament_id ='4';
update tournament set chinese_name = '伯恩茅斯' where tournament_id ='5';
update tournament set chinese_name = '美国公开赛' where tournament_id ='6';
update tournament set chinese_name = '布宜诺斯艾利斯' where tournament_id ='8';
update tournament set chinese_name = '蒙特卡洛大师赛' where tournament_id ='9';
update tournament set chinese_name = '汉堡' where tournament_id ='10';
update tournament set chinese_name = '罗马大师赛' where tournament_id ='11';
update tournament set chinese_name = '巴黎大师赛' where tournament_id ='12';
update tournament set chinese_name = '基茨比厄尔' where tournament_id ='13';
update tournament set chinese_name = '格施塔德' where tournament_id ='14';
update tournament set chinese_name = '费城' where tournament_id ='15';
update tournament set chinese_name = '杜塞尔多夫' where tournament_id ='16';
update tournament set chinese_name = '温布尔登' where tournament_id ='17';
update tournament set chinese_name = '霍巴特' where tournament_id ='18';
update tournament set chinese_name = '法网' where tournament_id ='19';
update tournament set chinese_name = '戴维斯杯 SAM' where tournament_id ='20';
update tournament set chinese_name = '戴维斯杯 WG' where tournament_id ='21';
update tournament set chinese_name = '戴维斯杯 EUR' where tournament_id ='22';
update tournament set chinese_name = '戴维斯杯 AME' where tournament_id ='23';
update tournament set chinese_name = '戴维斯杯 G2' where tournament_id ='24';
update tournament set chinese_name = '加拿大大师赛' where tournament_id ='25';
update tournament set chinese_name = '斯德哥尔摩' where tournament_id ='26';
update tournament set chinese_name = '墨尔本' where tournament_id ='27';
update tournament set chinese_name = '奥克兰' where tournament_id ='28';
update tournament set chinese_name = '伯恩茅斯' where tournament_id ='29';
update tournament set chinese_name = '加拉加斯' where tournament_id ='30';
update tournament set chinese_name = '印第安纳波利斯' where tournament_id ='31';
update tournament set chinese_name = '博斯塔德' where tournament_id ='32';
update tournament set chinese_name = '波士顿' where tournament_id ='33';
update tournament set chinese_name = '布里斯托尔' where tournament_id ='34';
update tournament set chinese_name = '悉尼' where tournament_id ='35';
update tournament set chinese_name = '阿默斯福特' where tournament_id ='36';
update tournament set chinese_name = '伦敦' where tournament_id ='37';
update tournament set chinese_name = '巴兰基亚' where tournament_id ='38';
update tournament set chinese_name = '戴维斯杯 G1' where tournament_id ='39';
update tournament set chinese_name = '南橙' where tournament_id ='40';
update tournament set chinese_name = '华盛顿' where tournament_id ='41';
update tournament set chinese_name = '波士顿' where tournament_id ='42';
update tournament set chinese_name = '博斯塔德' where tournament_id ='43';
update tournament set chinese_name = '卡萨布兰卡 WCT' where tournament_id ='44';
update tournament set chinese_name = '凤凰' where tournament_id ='45';
update tournament set chinese_name = '圣路易斯 WCT' where tournament_id ='46';
update tournament set chinese_name = '纽约' where tournament_id ='47';
update tournament set chinese_name = '路易斯 维尔' where tournament_id ='48';
update tournament set chinese_name = '年终总决赛' where tournament_id ='49';
update tournament set chinese_name = '纽约' where tournament_id ='50';
update tournament set chinese_name = '德黑兰' where tournament_id ='51';
update tournament set chinese_name = '巴黎' where tournament_id ='52';
update tournament set chinese_name = '芝加哥-2 WCT' where tournament_id ='53';
update tournament set chinese_name = '坦格伍德' where tournament_id ='54';
update tournament set chinese_name = '纽波特' where tournament_id ='55';
update tournament set chinese_name = '达拉斯' where tournament_id ='56';
update tournament set chinese_name = '悉尼户外' where tournament_id ='57';
update tournament set chinese_name = '科隆' where tournament_id ='58';
update tournament set chinese_name = '沃思堡' where tournament_id ='59';
update tournament set chinese_name = '尼斯' where tournament_id ='60';
update tournament set chinese_name = '里士满' where tournament_id ='61';
update tournament set chinese_name = '加拉加斯' where tournament_id ='62';
update tournament set chinese_name = '哥伦布' where tournament_id ='63';
update tournament set chinese_name = '伦敦 WCT' where tournament_id ='64';
update tournament set chinese_name = '温哥华' where tournament_id ='65';
update tournament set chinese_name = '魁北克' where tournament_id ='66';
update tournament set chinese_name = '美浓' where tournament_id ='67';
update tournament set chinese_name = '布鲁塞尔' where tournament_id ='68';
update tournament set chinese_name = '奥克兰' where tournament_id ='69';
update tournament set chinese_name = '萨克拉门托' where tournament_id ='70';
update tournament set chinese_name = '汉普顿' where tournament_id ='71';
update tournament set chinese_name = '迈阿密' where tournament_id ='72';
update tournament set chinese_name = '达拉斯 WCT' where tournament_id ='73';
update tournament set chinese_name = '夏洛特' where tournament_id ='74';
update tournament set chinese_name = '温布利' where tournament_id ='75';
update tournament set chinese_name = '索尔兹伯里' where tournament_id ='76';
update tournament set chinese_name = '休斯敦 WCT' where tournament_id ='77';
update tournament set chinese_name = '博洛尼亚' where tournament_id ='78';
update tournament set chinese_name = '梅肯' where tournament_id ='79';
update tournament set chinese_name = '卡塔尼亚' where tournament_id ='80';
update tournament set chinese_name = '巴勒莫' where tournament_id ='81';
update tournament set chinese_name = '戴维斯杯' where tournament_id ='82';
update tournament set chinese_name = '伦敦' where tournament_id ='83';
update tournament set chinese_name = '丹佛' where tournament_id ='84';
update tournament set chinese_name = '罗马 WCT' where tournament_id ='85';
update tournament set chinese_name = '洛杉矶' where tournament_id ='86';
update tournament set chinese_name = '埃森 WCT' where tournament_id ='87';
update tournament set chinese_name = '蒙特利尔 WCT' where tournament_id ='88';
update tournament set chinese_name = '阿拉莫 WCT' where tournament_id ='89';
update tournament set chinese_name = '鹿特丹' where tournament_id ='90';
update tournament set chinese_name = '休斯顿' where tournament_id ='91';
update tournament set chinese_name = '洛杉矶 WCT' where tournament_id ='92';
update tournament set chinese_name = '马德里' where tournament_id ='93';
update tournament set chinese_name = '克利夫兰' where tournament_id ='94';
update tournament set chinese_name = '新加坡' where tournament_id ='95';
update tournament set chinese_name = '拉斯维加斯' where tournament_id ='96';
update tournament set chinese_name = '约翰内斯堡-2' where tournament_id ='97';
update tournament set chinese_name = '布里斯托尔' where tournament_id ='98';
update tournament set chinese_name = '堪萨斯城' where tournament_id ='99';
update tournament set chinese_name = '得梅因' where tournament_id ='100';
update tournament set chinese_name = '悉尼系' where tournament_id ='101';
update tournament set chinese_name = '伦敦室内' where tournament_id ='102';
update tournament set chinese_name = '布雷顿' where tournament_id ='103';
update tournament set chinese_name = '奥马哈' where tournament_id ='104';
update tournament set chinese_name = '约翰内斯堡' where tournament_id ='105';
update tournament set chinese_name = '多伦多室内' where tournament_id ='106';
update tournament set chinese_name = '华盛顿-2' where tournament_id ='107';
update tournament set chinese_name = '罗巴 WCT' where tournament_id ='108';
update tournament set chinese_name = '杰克逊维尔' where tournament_id ='109';
update tournament set chinese_name = '西雅图' where tournament_id ='110';
update tournament set chinese_name = '伊斯特本' where tournament_id ='111';
update tournament set chinese_name = '布里斯班' where tournament_id ='112';
update tournament set chinese_name = '米兰' where tournament_id ='113';
update tournament set chinese_name = '拉哥斯达黎加' where tournament_id ='114';
update tournament set chinese_name = '大阪' where tournament_id ='115';
update tournament set chinese_name = '新德里' where tournament_id ='116';
update tournament set chinese_name = '马尼拉' where tournament_id ='117';
update tournament set chinese_name = '阿普托斯' where tournament_id ='118';
update tournament set chinese_name = '波尔图' where tournament_id ='120';
update tournament set chinese_name = '慕尼黑' where tournament_id ='121';
update tournament set chinese_name = '哥本哈根' where tournament_id ='122';
update tournament set chinese_name = '巴塞罗那' where tournament_id ='123';
update tournament set chinese_name = '布拉格' where tournament_id ='124';
update tournament set chinese_name = '柏林' where tournament_id ='125';
update tournament set chinese_name = '盐湖城' where tournament_id ='126';
update tournament set chinese_name = '卡尔加里' where tournament_id ='127';
update tournament set chinese_name = '克赖斯特彻奇' where tournament_id ='128';
update tournament set chinese_name = '帕拉默斯' where tournament_id ='129';
update tournament set chinese_name = '伯明翰' where tournament_id ='130';
update tournament set chinese_name = '杰克逊' where tournament_id ='131';
update tournament set chinese_name = '瓦伦西亚' where tournament_id ='132';
update tournament set chinese_name = '悉尼室内' where tournament_id ='133';
update tournament set chinese_name = '东京室内' where tournament_id ='134';
update tournament set chinese_name = '香港' where tournament_id ='135';
update tournament set chinese_name = '马德里' where tournament_id ='136';
update tournament set chinese_name = '芝加哥' where tournament_id ='137';
update tournament set chinese_name = '亚特兰大' where tournament_id ='138';
update tournament set chinese_name = '罗阿诺克' where tournament_id ='139';
update tournament set chinese_name = '诺丁汉' where tournament_id ='140';
update tournament set chinese_name = '棕榈泉' where tournament_id ='141';
update tournament set chinese_name = '瑟比顿' where tournament_id ='142';
update tournament set chinese_name = '雪松格罗夫' where tournament_id ='143';
update tournament set chinese_name = '孟买' where tournament_id ='144';
update tournament set chinese_name = '东京' where tournament_id ='145';
update tournament set chinese_name = '奥斯陆' where tournament_id ='146';
update tournament set chinese_name = '棕榈沙漠 WCT' where tournament_id ='147';
update tournament set chinese_name = '新奥尔良 WCT' where tournament_id ='148';
update tournament set chinese_name = '巴塞罗那 WCT' where tournament_id ='149';
update tournament set chinese_name = '圣彼得堡 WCT' where tournament_id ='150';
update tournament set chinese_name = '亚特兰大' where tournament_id ='151';
update tournament set chinese_name = '雅加达' where tournament_id ='152';
update tournament set chinese_name = '伊斯特本' where tournament_id ='153';
update tournament set chinese_name = '慕尼黑' where tournament_id ='154';
update tournament set chinese_name = '坦佩' where tournament_id ='155';
update tournament set chinese_name = '瓜鲁雅' where tournament_id ='156';
update tournament set chinese_name = '小石头' where tournament_id ='157';
update tournament set chinese_name = '阿德莱德' where tournament_id ='158';
update tournament set chinese_name = '华盛顿-2' where tournament_id ='159';
update tournament set chinese_name = '赫默尔亨普斯特德 WCT' where tournament_id ='160';
update tournament set chinese_name = '曼彻斯特' where tournament_id ='161';
update tournament set chinese_name = '都柏林' where tournament_id ='162';
update tournament set chinese_name = '维也纳' where tournament_id ='163';
update tournament set chinese_name = '檀香山' where tournament_id ='164';
update tournament set chinese_name = '北康威' where tournament_id ='165';
update tournament set chinese_name = '百慕大' where tournament_id ='166';
update tournament set chinese_name = '圣安东尼奥 WCT' where tournament_id ='167';
update tournament set chinese_name = '伊斯坦布尔' where tournament_id ='168';
update tournament set chinese_name = '纽约' where tournament_id ='169';
update tournament set chinese_name = '博卡西' where tournament_id ='170';
update tournament set chinese_name = '珀斯' where tournament_id ='171';
update tournament set chinese_name = '戴顿' where tournament_id ='172';
update tournament set chinese_name = '孟菲斯' where tournament_id ='173';
update tournament set chinese_name = '开罗' where tournament_id ='174';
update tournament set chinese_name = '墨尔本室内' where tournament_id ='175';
update tournament set chinese_name = '加尔各答' where tournament_id ='176';
update tournament set chinese_name = '斯德哥尔摩-WCT' where tournament_id ='177';
update tournament set chinese_name = '阿维莱斯' where tournament_id ='178';
update tournament set chinese_name = '什里夫波特' where tournament_id ='179';
update tournament set chinese_name = '费尔菲尔德' where tournament_id ='180';
update tournament set chinese_name = '巴哈马' where tournament_id ='181';
update tournament set chinese_name = '巴塞尔' where tournament_id ='182';
update tournament set chinese_name = '蒙特雷' where tournament_id ='183';
update tournament set chinese_name = '纽波特' where tournament_id ='184';
update tournament set chinese_name = '班加罗尔' where tournament_id ='185';
update tournament set chinese_name = '马德里' where tournament_id ='186';
update tournament set chinese_name = '百事可乐大满贯' where tournament_id ='187';
update tournament set chinese_name = '墨西哥城' where tournament_id ='188';
update tournament set chinese_name = 'WCT 挑战杯' where tournament_id ='189';
update tournament set chinese_name = '纽伦堡' where tournament_id ='190';
update tournament set chinese_name = '帕尔马' where tournament_id ='191';
update tournament set chinese_name = '喀土穆' where tournament_id ='192';
update tournament set chinese_name = '圣保罗' where tournament_id ='193';
update tournament set chinese_name = '拉各斯' where tournament_id ='194';
update tournament set chinese_name = '圣地亚哥' where tournament_id ='195';
update tournament set chinese_name = '哥伦布 WCT' where tournament_id ='196';
update tournament set chinese_name = '印第安纳波利斯 WCT' where tournament_id ='197';
update tournament set chinese_name = '罗马 WCT' where tournament_id ='198';
update tournament set chinese_name = 'WCT 挑战杯' where tournament_id ='199';
update tournament set chinese_name = '台北' where tournament_id ='200';
update tournament set chinese_name = '海洋城' where tournament_id ='201';
update tournament set chinese_name = '阿德莱德' where tournament_id ='202';
update tournament set chinese_name = '奥维多' where tournament_id ='203';
update tournament set chinese_name = '赫尔辛基' where tournament_id ='204';
update tournament set chinese_name = '冠军 WCT 锦标赛' where tournament_id ='205';
update tournament set chinese_name = '穆尔西亚' where tournament_id ='206';
update tournament set chinese_name = '洛杉矶' where tournament_id ='207';
update tournament set chinese_name = '苏黎世 WCT' where tournament_id ='208';
update tournament set chinese_name = '布宜诺斯艾利斯' where tournament_id ='209';
update tournament set chinese_name = '伯明翰 WCT' where tournament_id ='210';
update tournament set chinese_name = '弗吉尼亚海滩' where tournament_id ='211';
update tournament set chinese_name = '波哥大' where tournament_id ='212';
update tournament set chinese_name = '纳帕' where tournament_id ='213';
update tournament set chinese_name = '阿卡普尔科' where tournament_id ='214';
update tournament set chinese_name = '斯普林菲尔德' where tournament_id ='215';
update tournament set chinese_name = '普罗旺斯艾克斯' where tournament_id ='216';
update tournament set chinese_name = '拉古纳尼格尔' where tournament_id ='217';
update tournament set chinese_name = '澳大利亚公开赛-2' where tournament_id ='218';
update tournament set chinese_name = '东京户外' where tournament_id ='219';
update tournament set chinese_name = '萨拉索塔' where tournament_id ='220';
update tournament set chinese_name = '拉斯维加斯' where tournament_id ='221';
update tournament set chinese_name = '瓜达拉哈拉' where tournament_id ='222';
update tournament set chinese_name = '斯图加特' where tournament_id ='223';
update tournament set chinese_name = '哈特福德 WCT' where tournament_id ='224';
update tournament set chinese_name = '伯明翰' where tournament_id ='225';
update tournament set chinese_name = '斯托' where tournament_id ='226';
update tournament set chinese_name = '塔尔萨' where tournament_id ='227';
update tournament set chinese_name = '新奥尔良' where tournament_id ='228';
update tournament set chinese_name = '杜塞尔多夫' where tournament_id ='229';
update tournament set chinese_name = '森林丘陵' where tournament_id ='230';
update tournament set chinese_name = '圣何塞' where tournament_id ='231';
update tournament set chinese_name = '拉斐特' where tournament_id ='232';
update tournament set chinese_name = '林茨' where tournament_id ='233';
update tournament set chinese_name = '基多' where tournament_id ='234';
update tournament set chinese_name = '斯图加特大师赛' where tournament_id ='235';
update tournament set chinese_name = '路易斯 维尔' where tournament_id ='236';
update tournament set chinese_name = '特拉维夫' where tournament_id ='237';
update tournament set chinese_name = '幻影' where tournament_id ='238';
update tournament set chinese_name = '波尔多' where tournament_id ='239';
update tournament set chinese_name = '伯明翰' where tournament_id ='240';
update tournament set chinese_name = '蒙哥马利' where tournament_id ='241';
update tournament set chinese_name = '南希' where tournament_id ='242';
update tournament set chinese_name = '日内瓦' where tournament_id ='243';
update tournament set chinese_name = '中华民国' where tournament_id ='244';
update tournament set chinese_name = '维也纳' where tournament_id ='245';
update tournament set chinese_name = '曼谷' where tournament_id ='246';
update tournament set chinese_name = '圣保罗' where tournament_id ='247';
update tournament set chinese_name = '俄斯特拉发' where tournament_id ='248';
update tournament set chinese_name = '梅斯' where tournament_id ='249';
update tournament set chinese_name = '圣胡安' where tournament_id ='250';
update tournament set chinese_name = '休斯顿' where tournament_id ='251';
update tournament set chinese_name = '索菲亚' where tournament_id ='252';
update tournament set chinese_name = '坦帕' where tournament_id ='254';
update tournament set chinese_name = '布鲁塞尔' where tournament_id ='255';
update tournament set chinese_name = '威尼斯' where tournament_id ='257';
update tournament set chinese_name = '墨西哥城' where tournament_id ='259';
update tournament set chinese_name = '安科纳' where tournament_id ='260';
update tournament set chinese_name = '洛杉矶-2 WCT' where tournament_id ='261';
update tournament set chinese_name = '阿姆斯特丹 WCT' where tournament_id ='262';
update tournament set chinese_name = '多特蒙德 WCT' where tournament_id ='263';
update tournament set chinese_name = '滨湖采尔' where tournament_id ='264';
update tournament set chinese_name = '各国盖' where tournament_id ='265';
update tournament set chinese_name = '图卢兹' where tournament_id ='266';
update tournament set chinese_name = '马塞约' where tournament_id ='267';
update tournament set chinese_name = '斯特拉斯堡 WCT' where tournament_id ='268';
update tournament set chinese_name = '热那亚 WCT' where tournament_id ='269';
update tournament set chinese_name = '那不勒斯决赛 WCT' where tournament_id ='270';
update tournament set chinese_name = '德尔雷海滩 WCT' where tournament_id ='271';
update tournament set chinese_name = '巴伊亚' where tournament_id ='272';
update tournament set chinese_name = '希尔顿头 WCT' where tournament_id ='273';
update tournament set chinese_name = '墨尔本' where tournament_id ='274';
update tournament set chinese_name = '阿德莱德-2' where tournament_id ='275';
update tournament set chinese_name = '费拉拉' where tournament_id ='276';
update tournament set chinese_name = '里斯本' where tournament_id ='277';
update tournament set chinese_name = '底特律 WCT' where tournament_id ='278';
update tournament set chinese_name = '基茨比厄尔' where tournament_id ='279';
update tournament set chinese_name = '利文斯顿' where tournament_id ='280';
update tournament set chinese_name = '雷维索' where tournament_id ='281';
update tournament set chinese_name = '奥运会' where tournament_id ='282';
update tournament set chinese_name = '卢森堡' where tournament_id ='283';
update tournament set chinese_name = '马贝拉' where tournament_id ='284';
update tournament set chinese_name = '纽黑文' where tournament_id ='285';
update tournament set chinese_name = '迈尔斯堡' where tournament_id ='286';
update tournament set chinese_name = '迈阿密大师赛' where tournament_id ='287';
update tournament set chinese_name = '圣雷莫' where tournament_id ='288';
update tournament set chinese_name = '雅典' where tournament_id ='289';
update tournament set chinese_name = '拉斯维加斯' where tournament_id ='290';
update tournament set chinese_name = '印度水井大师赛' where tournament_id ='291';
update tournament set chinese_name = '首尔' where tournament_id ='292';
update tournament set chinese_name = '斯克内克塔迪' where tournament_id ='293';
update tournament set chinese_name = '蒙彼利埃' where tournament_id ='294';
update tournament set chinese_name = '黑麦溪' where tournament_id ='295';
update tournament set chinese_name = '底特律' where tournament_id ='296';
update tournament set chinese_name = '惠灵顿' where tournament_id ='297';
update tournament set chinese_name = '新加坡' where tournament_id ='298';
update tournament set chinese_name = '华沙' where tournament_id ='299';
update tournament set chinese_name = '布基亚斯' where tournament_id ='300';
update tournament set chinese_name = '马拉喀什' where tournament_id ='301';
update tournament set chinese_name = '大满贯杯' where tournament_id ='302';
update tournament set chinese_name = '乌马格' where tournament_id ='303';
update tournament set chinese_name = '莫斯科' where tournament_id ='304';
update tournament set chinese_name = '斯海尔托亨博斯' where tournament_id ='305';
update tournament set chinese_name = '长岛' where tournament_id ='306';
update tournament set chinese_name = '埃斯托利尔' where tournament_id ='307';
update tournament set chinese_name = '巴西利亚' where tournament_id ='308';
update tournament set chinese_name = '台北' where tournament_id ='309';
update tournament set chinese_name = '德尔雷海滩' where tournament_id ='310';
update tournament set chinese_name = '马赛' where tournament_id ='311';
update tournament set chinese_name = '萨拉戈萨' where tournament_id ='312';
update tournament set chinese_name = '迪拜' where tournament_id ='313';
update tournament set chinese_name = '北京' where tournament_id ='314';
update tournament set chinese_name = '吉隆坡-1' where tournament_id ='315';
update tournament set chinese_name = '多哈' where tournament_id ='316';
update tournament set chinese_name = '布加勒斯特' where tournament_id ='317';
update tournament set chinese_name = '哈莉' where tournament_id ='318';
update tournament set chinese_name = '布宜诺斯艾利斯' where tournament_id ='320';
update tournament set chinese_name = '瓦胡岛' where tournament_id ='321';
update tournament set chinese_name = '蒙得维的亚' where tournament_id ='322';
update tournament set chinese_name = '圣彼得堡' where tournament_id ='323';
update tournament set chinese_name = '瓦伦西亚' where tournament_id ='324';
update tournament set chinese_name = '布莱顿' where tournament_id ='325';
update tournament set chinese_name = '浦那' where tournament_id ='326';
update tournament set chinese_name = '胡志明市' where tournament_id ='327';
update tournament set chinese_name = '塔什干' where tournament_id ='328';
update tournament set chinese_name = '波士顿' where tournament_id ='329';
update tournament set chinese_name = '梅拉诺' where tournament_id ='330';
update tournament set chinese_name = '圣保罗' where tournament_id ='331';
update tournament set chinese_name = '马德里大师赛' where tournament_id ='332';
update tournament set chinese_name = '曼谷' where tournament_id ='333';
update tournament set chinese_name = '纽黑文' where tournament_id ='334';
update tournament set chinese_name = '萨格勒布' where tournament_id ='335';
update tournament set chinese_name = '孟买' where tournament_id ='336';
update tournament set chinese_name = '约翰内斯堡' where tournament_id ='337';
update tournament set chinese_name = '吉隆坡' where tournament_id ='338';
update tournament set chinese_name = '贝尔格莱德' where tournament_id ='339';
update tournament set chinese_name = '上海大师赛' where tournament_id ='340';
update tournament set chinese_name = '尼斯' where tournament_id ='341';
update tournament set chinese_name = '亚特兰大' where tournament_id ='342';
update tournament set chinese_name = '温斯顿-塞勒姆' where tournament_id ='343';
update tournament set chinese_name = '杜塞尔多夫' where tournament_id ='344';
update tournament set chinese_name = '波哥大' where tournament_id ='345';
update tournament set chinese_name = '深圳' where tournament_id ='346';
update tournament set chinese_name = '里约热内卢' where tournament_id ='347';
update tournament set chinese_name = '伊斯坦布尔' where tournament_id ='348';
update tournament set chinese_name = '基多' where tournament_id ='349';
update tournament set chinese_name = '埃斯托利尔' where tournament_id ='350';
update tournament set chinese_name = '索菲亚' where tournament_id ='351';
update tournament set chinese_name = '洛斯卡沃斯' where tournament_id ='352';
update tournament set chinese_name = '成都' where tournament_id ='353';
update tournament set chinese_name = '安特卫普' where tournament_id ='354';
update tournament set chinese_name = '布达佩斯' where tournament_id ='355';
update tournament set chinese_name = '里昂' where tournament_id ='356';
update tournament set chinese_name = '米兰' where tournament_id ='372';

COMMIT;